# SSH client policy for reaching the agent hosts (augtibcalcla, lanchamarcou)
# by their bare names.
#
# Why this exists: the agent hosts are enrolled in the headscale tailnet (see
# ../headscale), and the bare names resolve through resolv.conf's search
# domains - the tailnet domain is tried first (`augtibcalcla` ->
# `augtibcalcla.tailnet.internal` -> 100.64.0.3). While the tailnet data path
# is healthy that is fine, but when it is down (e.g. tailscaled wedged in its
# "TLS forced" control-dial state after the LAN router started publishing
# broken link-local AAAA records for the `.home` names, as it did on
# 2026-09-16) ssh would hang on the dead 100.64.0.x address instead of
# reaching the host over the LAN.
#
# These entries resolve the agents to their router-DNS LAN names instead,
# which always have working A records (the router serves them from its DHCP
# leases and tracks address changes; no hardcoded IPs). AddressFamily inet
# never picks the router's broken fe80:: AAAA records.
{ ... }:
{
  # lands in /etc/ssh/ssh_config, i.e. read by every user's ssh(1) and
  # regenerated by the system activation, so it survives the impermanence
  # rollback that wipes unlisted $HOME state (e.g. ~/.ssh)
  programs.ssh.extraConfig = ''
    Host augtibcalcla
      HostName augtibcalcla.home
      AddressFamily inet

    Host lanchamarcou
      HostName lanchamarcou.home
      AddressFamily inet
  '';
}
